# Generated by Django 4.0.4 on 2022-06-03 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='related departments'),
        ),
    ]
