# Generated by Django 4.0.4 on 2022-05-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_kebeleofficialtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KebeleOfficialTest',
        ),
    ]
