# Generated by Django 4.0.4 on 2022-06-03 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_is_active_account_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='department',
        ),
    ]
